<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.2.1" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="itext7" Version="9.1.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>    <ProjectReference Include="..\UserManagement.DBScriptExecuter\VGProducts.DBScriptExecuter.csproj" />
    <ProjectReference Include="..\VGProducts.Entities\VGProducts.Entities.csproj" />
    <ProjectReference Include="..\VGProducts.UnitTest\VGProducts.Unit.csproj" />
  </ItemGroup>

</Project>
